### ISSUE TITLE
Consider adding pricing info in the readme 

### ISSUE THREAD

**Issue by dreamorosi** [rehanvdm/serverless-website-analytics#18]
Great work with this solution!

It’d be great to have in the readme a section that discusses the average expected pricing for the solution.

For instance: running this solution with about 10M events/page views per month and a certain amount of dashboard interactions would cost you $$/month.

I think this would help people evaluate whether this is for them or not.

**Comment by rehanvdm** [comment]
Hey @dreamorosi I got around to this, have a look here https://github.com/rehanvdm/serverless-website-analytics/blob/main/docs/COST.md and let me know your thoughts. Thanks 🙂
